[meta]
name = "Nord"

[colors]
background       = "#2e3440"
background_dark  = "#242933"
background_alt   = "#3b4252"

foreground       = "#c5ceda"
foreground_muted = "#616e88"

red     = "#bf616a"
orange  = "#d08770"
yellow  = "#ebcb8b"
green   = "#a3be8c"
cyan    = "#8fbcbb"
blue    = "#81a1c1"
purple  = "#b48ead"
magenta = "#C5729A"

border    = "#4c566a"
selection = "#434c5e"
cursor    = "#d8dee9"

error   = "#bf616a"
warning = "#ebcb8b"
info    = "#81a1c1"
success = "#a3be8c"
