[meta]
name = "Abyss"

[colors]
background       = "#0a1116"
background_dark  = "#050a0e"
background_alt   = "#111c24"

foreground       = "#c4d0d6"
foreground_muted = "#667782"

red     = "#b76f73"
orange  = "#b58a68"
yellow  = "#b6aa72"
green   = "#7e9d83"
cyan    = "#69aaa8"
blue    = "#7199b8"
purple  = "#8f82a5"
magenta = "#a77991"

border    = "#293943"
selection = "#20313a"
cursor    = "#a2c8c4"

error   = "#b76f73"
warning = "#b6aa72"
info    = "#7199b8"
success = "#7e9d83"
