local M = {}

-- lua patterns; a group matching any of these is never reported
local ignore = {
  "^lualine_",     -- generated by lualine at runtime
  "^RedrawDebug",  -- debug-only
  "^NvimInvalid",  -- obscure
}

local function ignored(name)
  for _, pat in ipairs(ignore) do
    if name:match(pat) then return true end
  end
  return false
end

function M.run()
  local nvim = {}
  for name, rgb in pairs(vim.api.nvim_get_color_map()) do
    if name:match("^Nvim") then nvim[rgb] = true end
  end

  local out = {}
  for _, g in ipairs(vim.fn.getcompletion("", "highlight")) do
    if not ignored(g) then
      local hl = vim.api.nvim_get_hl(0, { name = g, link = false })
      if nvim[hl.fg] or nvim[hl.bg] or nvim[hl.sp] then out[#out + 1] = g end
    end
  end

  table.sort(out)
  print(#out .. " groups still use Nvim defaults:\n" .. table.concat(out, "\n"))
end

return M
