[meta]
name = "Cinder"

[colors]
background       = "#121110"
background_dark  = "#0a0908"
background_alt   = "#201e1b"

foreground       = "#d1cbc1"
foreground_muted = "#77716a"

red     = "#c16f5b"
orange  = "#c18458"
yellow  = "#bca264"
green   = "#7f9478"
cyan    = "#718d87"
blue    = "#727f8c"
purple  = "#8d7d88"
magenta = "#a37678"

border    = "#3b3732"
selection = "#302b26"
cursor    = "#d2a06c"

error   = "#c16f5b"
warning = "#bca264"
info    = "#727f8c"
success = "#7f9478"
