# foot.ini
[main]
include=/usr/share/foot/themes/onedark

font=Iosevka Variant 2:style=SemiBold:size=10

pad=2x2                             
initial-window-mode=windowed

[scrollback]
lines=1000
multiplier=5.0                     

[colors-dark]
cursor=000000 000000
#cursor=282c34 abb2bf 

[cursor]
style=underline
underline-thickness=2px
unfocused-style=none
blink=yes                        

[key-bindings]
spawn-terminal=none
spawn-terminal=Mod4+Return

[text-bindings]
# ctrl + backspace to delete previous word
# works by binding the hex of ^W
\x17=Control+BackSpace
# this one might not work; delete forwards
\x04=Control+Delete


[bell]
system=no
