[meta]
name = "Kanagawa"

[colors]
background       = "#1f1f28"
background_dark  = "#16161d"
background_alt   = "#2a2a37"

foreground       = "#dcd7ba"
foreground_muted = "#727169"

red     = "#c34043"
orange  = "#ffa066"
yellow  = "#c0a36e"
green   = "#76946a"
cyan    = "#7aa89f"
blue    = "#7e9cd8"
purple  = "#957fb8"
magenta = "#d27e99"

border    = "#54546d"
selection = "#2d4f67"
cursor    = "#c8c093"

error   = "#c34043"
warning = "#c0a36e"
info    = "#7e9cd8"
success = "#76946a"
