[meta]
name = "Moss"

[colors]
background       = "#252b27"
background_dark  = "#1d221f"
background_alt   = "#303832"

foreground       = "#d2d8cc"
foreground_muted = "#899489"

red     = "#c98282"
orange  = "#c99a73"
yellow  = "#c9b878"
green   = "#9caf88"
cyan    = "#88aaa0"
blue    = "#899eac"
purple  = "#a393aa"
magenta = "#b18d9d"

border    = "#424c43"
selection = "#39443a"
cursor    = "#b8c5a9"

error   = "#c98282"
warning = "#c9b878"
info    = "#899eac"
success = "#9caf88"
