[meta]
name = "Moss"

[colors]
background       = "#202522"
background_dark  = "#191d1b"
background_alt   = "#2a302c"

foreground       = "#c8cec8"
foreground_muted = "#737c75"

red     = "#b87878"
orange  = "#c29472"
yellow  = "#c5b77a"
green   = "#91a889"
cyan    = "#86a9a0"
blue    = "#8298a8"
purple  = "#9a8da0"
magenta = "#aa8795"

border    = "#414a44"
selection = "#354038"
cursor    = "#a8bca5"

error   = "#b87878"
warning = "#c5b77a"
info    = "#8298a8"
success = "#91a889"
