[meta]
name = "Sage"

[colors]
background       = "#282d29"
background_dark  = "#222722"
background_alt   = "#343b35"

foreground       = "#d0d5cf"
foreground_muted = "#858d85"

red     = "#bd7f7c"
orange  = "#c59a76"
yellow  = "#c9bd82"
green   = "#9caf91"
cyan    = "#91ada5"
blue    = "#8fa2b0"
purple  = "#a095a5"
magenta = "#b18d9b"

border    = "#4a534b"
selection = "#414b43"
cursor    = "#b4c5ad"

error   = "#bd7f7c"
warning = "#c9bd82"
info    = "#8fa2b0"
success = "#9caf91"
