[meta]
name = "Sage Dusk"

[colors]
background       = "#30372f"
background_dark  = "#272d27"
background_alt   = "#3b433a"

foreground       = "#d0d5c6"
foreground_muted = "#7f897b"

red     = "#bd7067"
orange  = "#bb8966"
yellow  = "#b6a269"
green   = "#8fa77a"
cyan    = "#79a19a"
blue    = "#7c9298"
purple  = "#9a8999"
magenta = "#b1848c"

border    = "#515b50"
selection = "#475147"
cursor    = "#d8ddcf"

error   = "#bd7067"
warning = "#b6a269"
info    = "#7c9298"
success = "#8fa77a"
