[meta]
name = "Gruvbox"

[colors]
background       = "#282828"
background_dark  = "#242424"
background_alt   = "#32302f"

foreground       = "#e7d7ad"
foreground_muted = "#665c54"

red     = "#cc241d"
orange  = "#fe8019"
yellow  = "#d79921"
green   = "#98971a"
cyan    = "#989d6a"
blue    = "#458588"
purple  = "#d3869b"
magenta = "#d3869b"

border    = "#504945"
selection = "#3c3836"
cursor    = "#ebdbb2"

error   = "#cc241d"
warning = "#d79921"
info    = "#d79921"
success = "#98971"
