[meta]
name = "Dracula"

[colors]
background       = "#282a36"
background_dark  = "#21222c"
background_alt   = "#44475a"

foreground       = "#f8f8f2"
foreground_muted = "#6272a4"

red     = "#ff5555"
orange  = "#ffb86c"
yellow  = "#f1fa8c"
green   = "#50fa7b"
cyan    = "#8be9fd"
blue    = "#8be9fd"
purple  = "#bd93f9"
magenta = "#ff79c6"

border    = "#6272a4"
selection = "#44475a"
cursor    = "#f8f8f2"

error   = "#ff5555"
warning = "#ffb86c"
info    = "#8be9fd"
success = "#50fa7b"
