[meta]
name = "Sage Light"

[colors]
background       = "#2c332f"
background_dark  = "#242a27"
background_alt   = "#383f3b"

foreground       = "#c8d0c9"
foreground_muted = "#78827a"

red     = "#b8797b"
orange  = "#c29272"
yellow  = "#c5bd83"
green   = "#91a88f"
cyan    = "#87a69b"
blue    = "#849b98"
purple  = "#9b909d"
magenta = "#aa8996"

border    = "#4a544e"
selection = "#414b45"
cursor    = "#b5c5b2"

error   = "#b8797b"
warning = "#c5bd83"
info    = "#849b98"
success = "#91a88f"
