[meta]
name = "Ayu Dark"

[colors]
background       = "#0b0e14"
background_dark  = "#070a0f"
background_alt   = "#11151c"

foreground       = "#bfbdb6"
foreground_muted = "#565b66"

red     = "#ea6c73"
orange  = "#ff8f40"
yellow  = "#f9af4f"
green   = "#7fd962"
cyan    = "#95e6cb"
blue    = "#59c2ff"
purple  = "#d2a6ff"
magenta = "#f07178"

border    = "#303540"
selection = "#273747"
cursor    = "#e6b450"

error   = "#ea6c73"
warning = "#f9af4f"
info    = "#59c2ff"
success = "#7fd962"
