[meta]
name = "Monokai"

[colors]
background       = "#272822"
background_dark  = "#1e1f1c"
background_alt   = "#3e3d32"

foreground       = "#f8f8f2"
foreground_muted = "#75715e"

red     = "#f92672"
orange  = "#fd971f"
yellow  = "#e6db74"
green   = "#a6e22e"
cyan    = "#66d9ef"
blue    = "#66d9ef"
purple  = "#ae81ff"
magenta = "#f92672"

border    = "#49483e"
selection = "#49483e"
cursor    = "#f8f8f0"

error   = "#f92672"
warning = "#e6db74"
info    = "#66d9ef"
success = "#a6e22e"
