[meta]
name = "Dracula Soft"

[colors]
background       = "#242530"
background_dark  = "#1d1e26"
background_alt   = "#343746"

foreground       = "#f2f2e9"
foreground_muted = "#767b9b"

red     = "#ff6e6e"
orange  = "#ffb86c"
yellow  = "#f8f89d"
green   = "#69ff94"
cyan    = "#8be9fd"
blue    = "#82aaff"
purple  = "#caa9fa"
magenta = "#ff8ad8"

border    = "#505469"
selection = "#414558"
cursor    = "#f8f8f2"

error   = "#ff6e6e"
warning = "#ffb86c"
info    = "#82aaff"
success = "#69ff94"
